In [ ]:
import spacy
import nltk
import tensorflow as tf
from textblob import TextBlob
from nltk.stem.porter import PorterStemmer

In [1]:
def chat(user_input):
    text=TextBlob(user_input)
    users=text.correct().string
    users=users.lower()
    print(users)
    replies={
        "how are you": "I am fine",
        "hello": "how i can help you"
    }
    if users in replies:
        return replies[users]
    else:
        return "Wrong Input"

In [2]:
user=input()
chat(user)

 hi


NameError: name 'TextBlob' is not defined

In [3]:
import spacy
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
nlp = spacy.load("en_core_web_sm")
text="we are good"
doc = nlp(text)
tokens = [token.text for token in doc]
ps=PorterStemmer()
stemming = [ps.stem(word) for word in tokens]
processed_text = ' '.join(stemming)
tfidf=TfidfVectorizer()
vectors=tfidf.fit_transform([processed_text]).toarray()
print(vectors)
replies={
        "how are you": "I am fine",
        "hello": "how i can help you"
    }
for i,j in replies.items():
    stemm=[ps.stem(word) for word in i.split()]
    procesed_text = ' '.join(stemm)
    vectors=tfidf.fit_transform([procesed_text]).toarray()
    print(vectors)
    print(stemm)

[[0.57735027 0.57735027 0.57735027]]
[[0.57735027 0.57735027 0.57735027]]
['how', 'are', 'you']
[[1.]]
['hello']


In [23]:
replies={
        "how are you": "I am fine",
        "hello": "how i can help you"
    }
for i,j in replies.items():
    stemm=[ps.stem(word) for word in i.split()]
    procesed_text = ' '.join(stemm)
    vectors=tfidf.fit_transform([procesed_text]).toarray()
    print(vectors)
    print(stemm)

[[0.57735027 0.57735027 0.57735027]]
['how', 'are', 'you']
[[1.]]
['hello']


In [25]:
import spacy
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# Load Spacy model
nlp = spacy.load("en_core_web_sm")

# Example text
text = "we are good"
doc = nlp(text)

# Tokenize and stem
tokens = [token.text for token in doc]
ps = PorterStemmer()
stemming = [ps.stem(word) for word in tokens]
processed_text = ' '.join(stemming)

# Prepare the corpus for TfidfVectorizer
corpus = [processed_text]

# Replies dictionary
replies = {
    "how are you": "I am fine",
    "hello why are you happy": "how i can help you"
}

# Process replies and add to corpus
for i in replies.keys():
    stemm = [ps.stem(word) for word in i.split()]
    processed_text = ' '.join(stemm)
    corpus.append(processed_text)

# Fit the TfidfVectorizer on the entire corpus
tfidf = TfidfVectorizer()
tfidf.fit(corpus)

# Transform the initial text
vectors = tfidf.transform([corpus[0]]).toarray()
print(f"Vector for the initial text: {vectors}")

# Transform and print vectors for the replies
for i, processed_text in zip(replies.keys(), corpus[1:]):
    vectors = tfidf.transform([processed_text]).toarray()
    print(f"Vector for '{i}': {vectors}")
    print(f"Stemmed: {processed_text.split()}")


Vector for the initial text: [[0.38537163 0.65249088 0.         0.         0.         0.65249088
  0.         0.        ]]
Vector for 'how are you': [[0.42544054 0.         0.         0.         0.72033345 0.
  0.         0.54783215]]
Stemmed: ['how', 'are', 'you']
Vector for 'hello why are you happy': [[0.29803159 0.         0.50461134 0.50461134 0.         0.
  0.50461134 0.38376993]]
Stemmed: ['hello', 'whi', 'are', 'you', 'happi']


# Using Machine learning NLP nltk + spacy + transformers + Sklearn

In [4]:
import spacy
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load Spacy model
nlp = spacy.load("en_core_web_sm")

# Tokenize and stem function
def tokenize_and_stem(text, nlp, ps):
    doc = nlp(text)
    tokens = [token.text for token in doc]
    stemming = [ps.stem(word) for word in tokens]
    return ' '.join(stemming)


# Initialize PorterStemmer
ps = PorterStemmer()
text=input()
corpus = [tokenize_and_stem(text, nlp, ps)]

# Replies dictionary
replies = {
    "how are you": "I am fine",
    "hello why are you happy": "how i can help you",
    "what is your name": "I am a evochat",
    "what do you do": "I chat with users",
    "how is the weather": "I do not have access to weather information",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "what is your favorite color": "I like all colors equally",
    "how old are you": "I am timeless",
    "where are you from": "I exist in the digital world",
    "what is your purpose": "To assist and provide information",
    "who created you": "I was created by evotechnology.us",
    "can you help me": "Of course! What do you need help with?",
    "tell me a fact": "Did you know? Honey never spoils",
    "what is the capital of France": "The capital of France is Paris",
    "what is the capital of Pak": "The capital of Pakistan is Islamabad",
    "do you like music": "I enjoy all kinds of music",
    "can you dance": "I can imagine dancing, but I cannot physically dance",
    "how can I learn programming": "There are many online resources and courses to learn programming",
    "what is AI": "AI stands for Artificial Intelligence",
    "do you have a family": "I am a virtual entity and do not have a family",
    "what are you": "I am a conversational AI chatbot",
    # Add more question-reply pairs as needed
}


# Process replies and add to corpus
for i in replies.keys():
    processed_text = tokenize_and_stem(i, nlp, ps)
    corpus.append(processed_text)
# Fit the TfidfVectorizer on the entire corpus
tfidf = TfidfVectorizer()
tfidf.fit(corpus)

# Transform the initial text and replies
vector_text = tfidf.transform([corpus[0]]).toarray()
vectors_replies = tfidf.transform(corpus[1:]).toarray()

# Calculate cosine similarities
cosine_similarities = cosine_similarity(vector_text, vectors_replies)

# Find the index of the most similar reply
most_similar_index = cosine_similarities.argmax()
print(most_similar_index)
# Get the corresponding reply
most_similar_reply_key = list(replies.keys())[most_similar_index]
reply = replies[most_similar_reply_key]

print(f"Input text: '{text}'")
print(f"Most similar reply: '{reply}'")


 hi how are you


0
Input text: 'hi how are you'
Most similar reply: 'I am fine'


# Using Deep Learning NLP Tensorflow

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample data
data = {
    "hi": "Hello!",
    "how are you": "I am fine, thank you!",
    "what is your name": "I am a chatbot.",
    "what do you do": "I chat with users.",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "what is the capital of Pak": "The capital of Pakistan is Islamabad"
}

# Prepare the data
input_texts = []
target_texts = []
for question, answer in data.items():
    input_texts.append(question)
    target_texts.append('<start> ' + answer + ' <end>')

# Tokenize the data
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(input_texts + target_texts)
input_sequences = tokenizer.texts_to_sequences(input_texts)
target_sequences = tokenizer.texts_to_sequences(target_texts)

# Pad the sequences
max_input_length = max([len(seq) for seq in input_sequences])
max_target_length = max([len(seq) for seq in target_sequences])
encoder_input_data = pad_sequences(input_sequences, maxlen=max_input_length, padding='post')
decoder_input_data = pad_sequences(target_sequences, maxlen=max_target_length, padding='post')

# Create decoder target data
vocab_size = len(tokenizer.word_index) + 1
decoder_target_data = np.zeros((len(target_sequences), max_target_length, vocab_size))
for i, seq in enumerate(target_sequences):
    for t, word_id in enumerate(seq):
        if t > 0:
            decoder_target_data[i, t - 1, word_id] = 1.0

# Build the model
latent_dim = 256

# Encoder
encoder_inputs = Input(shape=(None,))
encoder_embedding = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=latent_dim)(encoder_inputs)
encoder_lstm = LSTM(latent_dim, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_embedding)
encoder_states = [state_h, state_c]

# Decoder
decoder_inputs = Input(shape=(None,))
decoder_embedding = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=latent_dim)(decoder_inputs)
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)
decoder_dense = Dense(vocab_size, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

# Define the model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy')

# Train the model
model.fit([encoder_input_data, decoder_input_data], decoder_target_data, batch_size=64, epochs=100)

# Inference setup
encoder_model = Model(encoder_inputs, encoder_states)

decoder_state_input_h = Input(shape=(latent_dim,))
decoder_state_input_c = Input(shape=(latent_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_embedding, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

# Decode the sequence
def decode_sequence(input_seq):
    states_value = encoder_model.predict(input_seq)

    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = tokenizer.word_index['<start>']

    stop_condition = False
    decoded_sentence = ''
    while not stop_condition:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value)

        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_word = tokenizer.index_word[sampled_token_index]
        decoded_sentence += ' ' + sampled_word

        if sampled_word == '<end>' or len(decoded_sentence) > max_target_length:
            stop_condition = True

        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = sampled_token_index

        states_value = [h, c]

    return decoded_sentence.strip()

# Test the model
def chat(input_text):
    input_seq = tokenizer.texts_to_sequences([input_text])
    input_seq = pad_sequences(input_seq, maxlen=max_input_length, padding='post')
    decoded_sentence = decode_sequence(input_seq)
    print('Chatbot:', decoded_sentence)

# Example conversation
text=input()
chat(text)


In [2]:
pip install spacy

   ---------------------------------------- 0.0/11.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.8 MB 991.0 kB/s eta 0:00:12
   ---------------------------------------- 0.0/11.8 MB 991.0 kB/s eta 0:00:12
   ---------------------------------------- 0.1/11.8 MB 512.0 kB/s eta 0:00:23
   ---------------------------------------- 0.1/11.8 MB 655.8 kB/s eta 0:00:18
    --------------------------------------- 0.2/11.8 MB 748.1 kB/s eta 0:00:16
    --------------------------------------- 0.2/11.8 MB 748.1 kB/s eta 0:00:16
    --------------------------------------- 0.2/11.8 MB 686.8 kB/s eta 0:00:17
   - -------------------------------------- 0.3/11.8 MB 787.7 kB/s eta 0:00:15
   - -------------------------------------- 0.4/11.8 MB 825.0 kB/s eta 0:00:14
   - -------------------------------------- 0.4/11.8 MB 807.8 kB/s eta 0:00:15
   - -------------------------------------- 0.4/11.8 MB 860.2 kB/s eta